#!/bin/sh
LSC_FLAGS="--enable-num-framebuffers-quirk=true --disable-overlays=false"
if [ -d /etc/default/lsc-wrapper.d ]; then
    for f in /etc/default/lsc-wrapper.d/*; do . "$f"; done
fi
. /etc/environment
export ANDROID_ROOT
export MIR_SERVER_ENABLE_MIRCLIENT=1
export LD_PRELOAD=libtls-padding.so
export XDG_RUNTIME_DIR=/run
export WAYLAND_DISPLAY=wayland-syscomp
exec lomiri-system-compositor $LSC_FLAGS --console-provider=vt \
    --spinner=/usr/bin/lomiri-system-compositor-spinner "$@"
